apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ptf2qkkmo-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e194b5c62b5818bf4b338127c7d90063bbc70bd7@sha256:983e8e5455606766609479a0d9279aefccfbe707b60026fe0c01686a9fffad6a
          name: container-image
