apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ptf2qkkmo-go
  janus-idp.io/tekton: ptf2qkkmo-go
  backstage.io/kubernetes-id: ptf2qkkmo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ptf2qkkmo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
